export {default as Women} from './Women'
export {default as Men} from './Men'
export {default as PageNotFound} from './PageNotFound'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as ForgotPassword} from './ForgotPassword'
export {default as JeanProduct} from './JeanProduct'
export {default as JeanProductDetails} from './JeanProductDetails'